### ISSUE TITLE
Issue loading jade templates

### ISSUE THREAD

**Issue by miffels** [webpack/enhanced-require#1]
Hi guys,

I am currently facing an issue with enhanced-require or the jade loader built in webpack respectively. Quite frankly, I am not sure in which project to file this issue since I have difficulties figuring out which component is to blame, assuming I made no mistake in the first place.

My app is running on `node 0.8.11` with `webpack 0.7.8`, `jade 0.27.6` and `enhanced-require 0.4.0-beta3`. The javascript file I am trying to run in `node` contains the following statements only:

```
// project_root/src/main.js
'use strict';
require = require('enhanced-require')(module);

var template = require('./client/view/test.jade');
```

Unfortunately, when I try to execute it, the following error is thrown:

```
$ node src/main

Error: Loader throwed exeception: TypeError: Object #<Object> has no method 'apply'
    at nextLoader (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\node_modules\enhanced-require\lib\execLoaders.js:146:40)
    at execLoaders (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\node_modules\enhanced-require\lib\execLoaders.js:41:14)
    at Function.module.exports.sync (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\node_modules\enhanced-require\lib\execLoaders.js:201:2)
    at Object.theRequire (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\node_modules\enhanced-require\lib\require.js:81:17)
    at Object.<anonymous> (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\src\main.js:3:16)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at nextLoader (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\node_modules\enhanced-require\lib\execLoaders.js:168:15)
    at execLoaders (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\node_modules\enhanced-require\lib\execLoaders.js:41:14)
    at Function.module.exports.sync (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\node_modules\enhanced-require\lib\execLoaders.js:201:2)
    at Object.theRequire (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\node_modules\enhanced-require\lib\require.js:81:17)
    at Object.<anonymous> (C:\Users\d053411\Documents\Aptana Studio 3 Workspace\yarse\src\main.js:3:16)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
```

Can you reproduce the errors? Or might I have missed some important configuration?

Best regards,
Michael

**Comment by sokra** [comment]
You need the https://github.com/webpack/jade-loader module.

**Comment by miffels** [comment]
Sorry, now I see that originally I had another error, then removed `jade-loader` from my node_modules folder, which gave me the error above. Now, I have (and had before) the following issue with `jade-loader 0.2.0`:

```
$ node src/main

Error: Module "<project root>\node_modules\jade-loader\node_modules\jade\lib\runtime" not found in context "<project root>\src\client\view"
  Error: Non of this files exists: <project root>\node_modules\jade-loader\node_modules\jade\lib\runtime, <project root>\node_modules\jade-loader\node_modules\jade\lib\runtime.node, <project root>\node_
modules\jade-loader\node_modules\jade\lib\runtime.er.js, <project root>\node_modules\jade-loader\node_modules\jade\lib\runt
ime.js
    at finalResult (<project root>\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\resolve.js:24:13)
    at bothDone (<project root>\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\resolve.js:352:4)
    at loadAsFileOrDirectoryDirectoryResultCallback (<project root>\node_modules\enhanced-require\node_modules\enhanced-res
olve\lib\resolve.js:345:17)
    at <project root>\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\resolve.js:291:11
    at throttledFunction (<project root>\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\createThrottledFun
ction.js:45:5)
    at loadAsDirectory (<project root>\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\resolve.js:289:27)
    at loadAsFileOrDirectory (<project root>\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\resolve.js:339
:2)
    at resolve (<project root>\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\resolve.js:54:4)
    at doResolve (<project root>\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\resolve.js:67:3)
    at Function.module.exports.sync (<project root>\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\resolve
.js:218:2)
```

Finally I realized that my mistake was the following: It appears that `jade-loader` does not expect an earlier `jade` installation. When I removed `jade` from my `node_modules` folder and `npm install`-ed `jade-loader` again, everything worked as expected. I see that I do not need a separate `jade` installation as  `enhanced-require` needs the loader anyway and `webpack` already has it integrated. Nevertheless, I found this quite irritating since I tried some `jade` basics before in "plain node" and did not expect to experience a conflict between that and `jade-loader`.

Anyway, thank you very much for your quick response: It led me to the rather obvious mistake I made earlier.

Have a good night,
Michael
