### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL with java node_module

### ISSUE THREAD

**Issue by totty90** [webpack/enhanced-require#14]
I'm using the [webdriver-sync]() webdriver module which uses the `java` module. With the default node.js require everything works as expected. With the enhanced require the result is this:

```
C:\app\node_modules\webdriver-sync\node_modules\java\build\Release\nodejavabridge_bindings.node:1
nction (exports, require, define, module, __filename, __dirname) {MZï¿½
                                                                    ^
SyntaxError: Unexpected token ILLEGAL
  at NormalModuleMixin.Module._compile (C:\app\node_modules\enhanced-require\lib\Module.js:52:24)
  at RequireContext.theRequire (C:\app\node_modules\enhanced-require\lib\RequireContext.js:169:10)
  at C:\app\node_modules\webdriver-sync\node_modules\java\lib\nodeJavaBridge.js:7:16
  at NormalModuleMixin.Module._compile (C:\app\node_modules\enhanced-require\lib\Module.js:53:18)
  at RequireContext.theRequire (C:\app\node_modules\enhanced-require\lib\RequireContext.js:169:10)
  at C:\app\node_modules\webdriver-sync\node_modules\java\index.js:2:18
  at NormalModuleMixin.Module._compile (C:\app\node_modules\enhanced-require\lib\Module.js:53:18)
  at RequireContext.theRequire (C:\app\node_modules\enhanced-require\lib\RequireContext.js:169:10)
  at C:\app\node_modules\webdriver-sync\src\webdriver-sync.js:3:12
  at NormalModuleMixin.Module._compile (C:\app\node_modules\enhanced-require\lib\Module.js:53:18)
  at RequireContext.theRequire (C:\app\node_modules\enhanced-require\lib\RequireContext.js:169:10)
  at Object.<anonymous> (C:\app\tests\integration\support\World.js:15:10)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.module.exports (C:\app\tests\integration\steps\init.steps.js:2:18)
  at Array.forEach (native)
  at Object.<anonymous> (C:\app\tests\test.js:4:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

I notice the `MZï¿½` and happens because is a binary.

**Comment by totty90** [comment]
Quick fix: I've added the originalRequire to the enhancedRequire and loaded the webdriver-sync with the original node.js require.
